version: '3.8'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_DATABASE=technical_test
      - MYSQL_ROOT_PASSWORD=technical_test
      - MYSQL_USER=technical_test
      - MYSQL_PASSWORD=technical_test
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-init-scripts/mysql-init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql-init-scripts/technical_test-schema.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./mysql-init-scripts/technical_test-data.sql:/docker-entrypoint-initdb.d/3.sql"

