USE technical_test;
INSERT INTO COURSES (NAME, DESCRIPTION, START, END) VALUES ('Course 1', 'Description 1', '2024-04-24 08:00:00', '2024-04-24 18:00:00');
INSERT INTO COURSES (NAME, DESCRIPTION, START, END) VALUES ('Course 2', 'Description 2', '2024-04-24 08:00:00', '2024-04-24 18:00:00');

INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('John', 'Doe', 'john.doe@mail.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Jane', 'Doe', 'jane.doe@mail.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Alice', 'Doe', 'alice.doe@mail.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Bob', 'Doe', 'bob.doe@mail.com');

INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT) VALUES (1, 1, 0, NULL, 0, NULL, NULL, NULL, NULL);
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT) VALUES (1, 2, 0, NULL, 0, NULL, NULL, NULL, NULL);
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT) VALUES (1, 3, 0, NULL, 0, NULL, NULL, NULL, NULL);
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT) VALUES (1, 4, 0, NULL, 0, NULL, NULL, NULL, NULL);

INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT) VALUES (2, 1, 0, NULL, 0, NULL, NULL, NULL, NULL);
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT) VALUES (2, 3, 0, NULL, 0, NULL, NULL, NULL, NULL);
