INSERT INTO COURSES (NAME, DESCRIPTION, START, END, DATE_CREATED, DATE_UPDATED) VALUES ('Course 1', 'Description 1', '2024-04-24 08:00:00', '2024-04-24 18:00:00', DATETIME('now'), DATETIME('now'));
INSERT INTO COURSES (NAME, DESCRIPTION, START, END, DATE_CREATED, DATE_UPDATED) VALUES ('Course 2', 'Description 2', '2024-04-24 08:00:00', '2024-04-24 18:00:00', DATETIME('now'), DATETIME('now'));

INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL, DATE_CREATED, DATE_UPDATED) VALUES ('John', 'Doe', 'john.doe@mail.com', DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL, DATE_CREATED, DATE_UPDATED) VALUES ('Jane', 'Doe', 'jane.doe@mail.com', DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL, DATE_CREATED, DATE_UPDATED) VALUES ('Alice', 'Doe', 'alice.doe@mail.com', DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL, DATE_CREATED, DATE_UPDATED) VALUES ('Bob', 'Doe', 'bob.doe@mail.com', DATETIME('now'), DATETIME('now'));

INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT, DATE_CREATED, DATE_UPDATED) VALUES (1, 1, 0, NULL, 0, NULL, NULL, NULL, NULL, DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT, DATE_CREATED, DATE_UPDATED) VALUES (1, 2, 0, NULL, 0, NULL, NULL, NULL, NULL, DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT, DATE_CREATED, DATE_UPDATED) VALUES (1, 3, 0, NULL, 0, NULL, NULL, NULL, NULL, DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT, DATE_CREATED, DATE_UPDATED) VALUES (1, 4, 0, NULL, 0, NULL, NULL, NULL, NULL, DATETIME('now'), DATETIME('now'));

INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT, DATE_CREATED, DATE_UPDATED) VALUES (2, 1, 0, NULL, 0, NULL, NULL, NULL, NULL, DATETIME('now'), DATETIME('now'));
INSERT INTO STUDENT_STATES (COURSE_ID, STUDENT_ID, STATE, EXCLUDED, DELAY, EARLY_DEPARTURE, TIMESTAMP, SIGNATURE, COMMENT, DATE_CREATED, DATE_UPDATED) VALUES (2, 3, 0, NULL, 0, NULL, NULL, NULL, NULL, DATETIME('now'), DATETIME('now'));
